In [35]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [70]:
### Reading train and test data ###
test_df= pd.read_csv('unfinished.csv', sep=',', header=0)
train_df= pd.read_csv('finished.csv', sep=',', header=0)

### merging data ###
df = pd.concat([train_df, test_df], ignore_index=True)
df_processed = df.copy(deep=True)

In [71]:
### changing some of the categories to numerical values ###
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

le.fit(df_processed.country)
df_processed.country = le.transform(df.country)

le.fit(df_processed.currency)
df_processed.currency = le.transform(df.currency)

le.fit(df_processed.staff_pick)
df_processed.staff_pick = le.transform(df.staff_pick)

le.fit(df_processed.category)
df_processed.category = le.transform(df.category)

le.fit(df_processed.location)
df_processed.location = le.transform(df.location)

le.fit(df_processed.is_starrable)
df_processed.is_starrable = le.transform(df.is_starrable)

le.fit(df_processed.disable_communication)
df_processed.disable_communication = le.transform(df.disable_communication)

# checking the dataframes
df_processed.describe()
df.describe()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

,backers_count,category,country,creator,currency,disable_communication,goal,is_starrable,staff_pick,usd_pledged,location,blurb_length,duration
count,177768.000000,177768.000000,177768.000000,1.777680e+05,177768.000000,177768.000000,1.777680e+05,177768.000000,177768.000000,1.777680e+05,177768.000000,177768.000000,177768.000000
mean,129.263743,84.226773,18.175847,1.073674e+09,11.068291,0.003381,4.556443e+04,0.020831,0.126260,1.065866e+04,7085.810860,19.360430,33.611977
std,925.448230,47.757950,5.832286,6.198828e+08,3.893460,0.058047,1.208635e+06,0.142817,0.332143,8.128235e+04,3987.920746,4.845785,12.721739
min,0.000000,0.000000,0.000000,3.000000e+00,0.000000,0.000000,1.000000e-02,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.000000
25%,3.000000,46.000000,21.000000,5.383356e+08,13.000000,0.000000,1.600000e+03,0.000000,0.000000,6.852201e+01,3225.000000,17.000000,30.000000
50%,22.000000,87.000000,21.000000,1.073209e+09,13.000000,0.000000,5.000000e+03,0.000000,0.000000,1.226000e+03,7307.000000,20.000000,30.000000
75%,77.000000,123.000000,21.000000,1.610515e+09,13.000000,0.000000,1.334045e+04,0.000000,0.000000,5.550000e+03,10264.000000,23.000000,36.000000
max,105857.000000,167.000000,21.000000,2.147465e+09,13.000000,1.000000,1.523501e+08,1.000000,1.000000,1.026685e+07,14398.000000,35.000000,92.000000

,backers_count,creator,goal,usd_pledged,blurb_length,duration
count,177768.000000,1.777680e+05,1.777680e+05,1.777680e+05,177768.000000,177768.000000
mean,129.263743,1.073674e+09,4.556443e+04,1.065866e+04,19.360430,33.611977
std,925.448230,6.198828e+08,1.208635e+06,8.128235e+04,4.845785,12.721739
min,0.000000,3.000000e+00,1.000000e-02,0.000000e+00,0.000000,1.000000
25%,3.000000,5.383356e+08,1.600000e+03,6.852201e+01,17.000000,30.000000
50%,22.000000,1.073209e+09,5.000000e+03,1.226000e+03,20.000000,30.000000
75%,77.000000,1.610515e+09,1.334045e+04,5.550000e+03,23.000000,36.000000
max,105857.000000,2.147465e+09,1.523501e+08,1.026685e+07,35.000000,92.000000

In [74]:
## dropping unnecessary categories from the data table ##
drop_list = ['urls']
df_processed.drop(drop_list, axis=1, inplace = True)

In [75]:
## saving processed data to new csv files ##
finished_proc = df_processed.loc[df_processed.state != 'live']
unfinished_proc = df_processed.loc[df_processed.state == 'live']

finished_proc.to_csv('finished_processed.csv', index = False)
unfinished_proc.to_csv('unfinished_processed.csv', index = False)